In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\Lenovo\OneDrive\Documents\covid.csv')
df.sample(5)

df1=df.drop('City',axis=1)
df1

    Age  Gender Fever Cough       State Has Covid
0    25    Male   Yes  High  California       Yes
1    32  Female    No  Mild       Texas        No
2    45    Male   Yes  High     Florida       Yes
3    28  Female    No   Low    Illinois        No
4    55    Male   Yes  High    New York       Yes
..  ...     ...   ...   ...         ...       ...
83   63  Female   Yes  High    Illinois       Yes
84   43    Male   Yes  High    New York       Yes
85   48  Female    No   Low  California        No
86   41    Male   Yes  Mild       Texas       Yes
87   32  Female   Yes  High     Florida       Yes

[88 rows x 6 columns]

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df1.iloc[:,1:],df1.iloc[:,-1:],test_size=0.2,random_state=2)

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
transformer=ColumnTransformer(transformers=[
    ('trans1',OneHotEncoder(sparse_output=False,drop='first'),['Gender']),
    ('trans2',OneHotEncoder(sparse_output=False,drop='first'),['Fever']),
    ('trans3',OrdinalEncoder(categories=[['Low','Mild','High']]),['Cough']),
    ('trans4',OneHotEncoder(sparse_output=False,drop='first'),['State'])
],remainder='passthrough')

In [6]:
X_trained=transformer.fit_transform(X_train)

In [7]:
# Assuming `X_trained` is the result of your transformation (e.g., from ColumnTransformer or OneHotEncoder)
# Get the feature names after transformation
feature_names = transformer.get_feature_names_out(input_features=X_train.columns)

# Create the final DataFrame with the correct column names
final = pd.DataFrame(X_trained, columns=feature_names)

# View the final DataFrame
final

,trans1__Gender_Male,trans2__Fever_Yes,trans3__Cough,trans4__State_Florida,trans4__State_Illinois,trans4__State_New York,trans4__State_Texas,remainder__Has Covid
0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,Yes
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,No
2,1.0,1.0,2.0,0.0,1.0,0.0,0.0,Yes
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
4,0.0,1.0,2.0,1.0,0.0,0.0,0.0,Yes
...,...,...,...,...,...,...,...,...
65,0.0,1.0,1.0,0.0,1.0,0.0,0.0,Yes
66,1.0,0.0,0.0,1.0,0.0,0.0,0.0,No
67,1.0,1.0,2.0,1.0,0.0,0.0,0.0,Yes
68,0.0,1.0,1.0,0.0,0.0,0.0,0.0,Yes
69,1.0,1.0,2.0,0.0,0.0,0.0,0.0,Yes

In [8]:
#  for writing in more modern and readable approach
from sklearn.compose import make_column_transformer

In [9]:
preprocessor=make_column_transformer(
    (OneHotEncoder(sparse_output=False,drop='first'),['Gender']),
    (OneHotEncoder(sparse_output=False,drop='first'),['Fever']),
    (OrdinalEncoder(categories=[['Low','Mild','High']]),['Cough']),
    (OneHotEncoder(sparse_output=False,drop='first'),['State']),
    remainder='passthrough'
)

In [10]:
X_train_preprocessed=preprocessor.fit_transform(X_train)
X_test_preprocessed=preprocessor.transform(X_test)

In [12]:
feature_names=preprocessor.get_feature_names_out(input_features=X_train.columns)

fin=pd.DataFrame(X_train_preprocessed,columns=feature_names)
fin

,onehotencoder-1__Gender_Male,onehotencoder-2__Fever_Yes,ordinalencoder__Cough,onehotencoder-3__State_Florida,onehotencoder-3__State_Illinois,onehotencoder-3__State_New York,onehotencoder-3__State_Texas,remainder__Has Covid
0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,Yes
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,No
2,1.0,1.0,2.0,0.0,1.0,0.0,0.0,Yes
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No
4,0.0,1.0,2.0,1.0,0.0,0.0,0.0,Yes
...,...,...,...,...,...,...,...,...
65,0.0,1.0,1.0,0.0,1.0,0.0,0.0,Yes
66,1.0,0.0,0.0,1.0,0.0,0.0,0.0,No
67,1.0,1.0,2.0,1.0,0.0,0.0,0.0,Yes
68,0.0,1.0,1.0,0.0,0.0,0.0,0.0,Yes
69,1.0,1.0,2.0,0.0,0.0,0.0,0.0,Yes